[package]
name = "stele"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
env_logger = "0.11.10"
fontdb = "0.23.0"
freetype-rs = { version = "0.38.0", features = ["bundled"] }
log = "0.4.29"
ordered-float = "5.3.0"
pollster = "0.4.0"
wgpu = "29.0.1"
winit = "0.30"
