//! Shared action and view-update payloads crossing the winit/async boundary.

use std::ops::{BitOr, BitOrAssign};
use std::time::Instant;

use crate::scene::instance::AtlasRegion;
use crate::scene::{SceneBuffer, SceneFrameMetadata};

/// Wake-up event delivered through the winit event-loop proxy.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum WakeEvent {
    Wake,
}

/// High-level mouse button independent of the windowing backend.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum MouseButtonKind {
    Left,
    Right,
    Middle,
    Back,
    Forward,
    Other(u16),
}

/// High-level scroll payload independent of the windowing backend.
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) enum MouseScroll {
    LineDelta { x: f32, y: f32 },
    PixelDelta { x: f64, y: f64 },
}

/// Backend-agnostic keyboard modifiers snapshot.
#[derive(Debug, Default, Clone, Copy, Eq, PartialEq)]
pub(crate) struct KeyModifiers(u8);

#[allow(dead_code)]
impl KeyModifiers {
    pub(crate) const NONE: Self = Self(0);
    pub(crate) const SHIFT: Self = Self(1 << 0);
    pub(crate) const CONTROL: Self = Self(1 << 1);
    pub(crate) const ALT: Self = Self(1 << 2);
    pub(crate) const SUPER: Self = Self(1 << 3);

    /// Returns whether no modifier bits are active.
    pub(crate) fn is_empty(self) -> bool {
        self.0 == 0
    }

    /// Returns whether all bits from `other` are active in this snapshot.
    pub(crate) fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }

    /// Returns whether the shift key is active in this snapshot.
    pub(crate) fn shift(self) -> bool {
        self.contains(Self::SHIFT)
    }

    /// Returns whether the control key is active in this snapshot.
    pub(crate) fn control(self) -> bool {
        self.contains(Self::CONTROL)
    }

    /// Returns whether the alt key is active in this snapshot.
    pub(crate) fn alt(self) -> bool {
        self.contains(Self::ALT)
    }

    /// Returns whether the super key is active in this snapshot.
    pub(crate) fn super_key(self) -> bool {
        self.contains(Self::SUPER)
    }

    /// Sets or clears one modifier bit.
    pub(crate) fn set(&mut self, flag: Self, enabled: bool) {
        if enabled {
            self.0 |= flag.0;
        } else {
            self.0 &= !flag.0;
        }
    }
}

impl BitOr for KeyModifiers {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0 | rhs.0)
    }
}

impl BitOrAssign for KeyModifiers {
    fn bitor_assign(&mut self, rhs: Self) {
        self.0 |= rhs.0;
    }
}

/// Backend-agnostic keyboard event kind.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum KeyEventKind {
    Press,
    Release,
    Repeat,
}

/// Backend-agnostic key code carried by keyboard input facts.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum KeyCode {
    Char(char),
    Enter,
    Tab,
    Escape,
    Backspace,
    Delete,
    Insert,
    Shift,
    Control,
    Alt,
    Super,
    Left,
    Right,
    Up,
    Down,
    Home,
    End,
    PageUp,
    PageDown,
    F(u8),
    Unknown,
}

/// Backend-agnostic keyboard input fact.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) struct KeyEvent {
    pub(crate) code: KeyCode,
    pub(crate) modifiers: KeyModifiers,
    pub(crate) kind: KeyEventKind,
}

/// Backend-agnostic mouse input fact.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct MouseEvent {
    pub(crate) kind: MouseEventKind,
    pub(crate) logical_position: Option<[f32; 2]>,
    pub(crate) scroll_delta: Option<MouseScroll>,
    pub(crate) modifiers: KeyModifiers,
    pub(crate) event_time: Instant,
}

/// Backend-agnostic mouse event kind.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum MouseEventKind {
    Down(MouseButtonKind),
    Up(MouseButtonKind),
    Drag(MouseButtonKind),
    Moved,
    ScrollUp,
    ScrollDown,
    ScrollLeft,
    ScrollRight,
}

/// Typed input fact crossing the winit/async boundary.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum InputEvent {
    Key(KeyEvent),
    Mouse(MouseEvent),
    // Phase 4 consumes paste facts in the store before a platform clipboard producer is wired in.
    #[allow(dead_code)]
    Paste(String),
    CursorLeft,
    FocusChanged {
        focused: bool,
    },
}

/// Unified input action sent from winit into the async store.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Action {
    Input {
        event: InputEvent,
    },
    Resize {
        width: u32,
        height: u32,
        scale_factor: f32,
        viewport_revision: u64,
        event_time: Instant,
    },
    Shutdown,
}

/// One atlas texture region write generated by the async logical atlas.
#[derive(Clone, Debug)]
pub(crate) struct AtlasPatch {
    pub(crate) region: AtlasRegion,
    pub(crate) pixels: Vec<u8>,
}

impl AtlasPatch {
    /// Creates one atlas patch whose pixel payload is already RGBA8.
    pub(crate) fn new(region: AtlasRegion, pixels: Vec<u8>) -> Self {
        Self { region, pixels }
    }
}

/// Scene frame emitted by the async store toward the view.
pub(crate) struct SceneFrame {
    buffer: Box<SceneBuffer>,
}

impl SceneFrame {
    /// Wraps one self-contained scene buffer for transport to the view thread.
    pub(crate) fn new(buffer: Box<SceneBuffer>) -> Self {
        Self { buffer }
    }

    /// Consumes the frame and returns its scene buffer ownership.
    pub(crate) fn into_buffer(self) -> Box<SceneBuffer> {
        self.buffer
    }

    /// Returns the scene metadata without exposing ownership.
    pub(crate) fn metadata(&self) -> SceneFrameMetadata {
        self.buffer.metadata()
    }
}

impl std::fmt::Debug for SceneFrame {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SceneFrame")
            .field("metadata", &self.metadata())
            .finish()
    }
}

/// One atlas update emitted by the async store toward the view.
#[derive(Clone, Debug)]
pub(crate) struct AtlasUpdate {
    pub(crate) generation: u64,
    pub(crate) requested_atlas_size: Option<u32>,
    pub(crate) patches: Vec<AtlasPatch>,
}

impl AtlasUpdate {
    /// Creates an empty atlas update for one logical atlas generation.
    pub(crate) fn new(generation: u64) -> Self {
        Self {
            generation,
            requested_atlas_size: None,
            patches: Vec::new(),
        }
    }
}

/// Unified async-to-view payload. Atlas and scene lifecycles are independent.
#[derive(Debug)]
pub(crate) enum ViewUpdate {
    Atlas(AtlasUpdate),
    Scene(SceneFrame),
}

#[cfg(test)]
mod tests {
    use super::KeyModifiers;

    #[test]
    fn key_modifiers_support_runtime_queries() {
        let modifiers = KeyModifiers::CONTROL | KeyModifiers::SHIFT;

        assert!(!modifiers.is_empty());
        assert!(modifiers.contains(KeyModifiers::CONTROL));
        assert!(modifiers.contains(KeyModifiers::CONTROL | KeyModifiers::SHIFT));
        assert!(modifiers.control());
        assert!(modifiers.shift());
        assert!(!modifiers.alt());
        assert!(!modifiers.super_key());
    }
}
