//! Shared action and scene-diff payloads crossing the winit/async boundary.

use crate::renderer::atlas::AtlasRegion;
use crate::scene::{BlockId, BlockSceneBatch};

/// Wake-up event delivered through the winit event-loop proxy.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum WakeEvent {
    Wake,
}

/// High-level button state independent of the windowing backend.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum ButtonState {
    Pressed,
    Released,
}

/// High-level mouse button independent of the windowing backend.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum MouseButtonKind {
    Left,
    Right,
    Middle,
    Back,
    Forward,
    Other(u16),
}

/// High-level scroll payload independent of the windowing backend.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum MouseScroll {
    LineDelta { x: f32, y: f32 },
    PixelDelta { x: f64, y: f64 },
}

/// Unified input action sent from winit into the async store.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Action {
    KeyInput {
        text: String,
    },
    MouseButton {
        state: ButtonState,
        button: MouseButtonKind,
    },
    MouseMove {
        x: f64,
        y: f64,
    },
    MouseScroll {
        delta: MouseScroll,
    },
    Resize {
        width: u32,
        height: u32,
        scale_factor: f32,
        viewport_revision: u64,
    },
    Shutdown,
}

/// One atlas texture region write generated by the async logical atlas.
#[derive(Clone, Debug)]
pub(crate) struct AtlasPatch {
    pub(crate) region: AtlasRegion,
    pub(crate) pixels: Vec<u8>,
}

impl AtlasPatch {
    /// Creates one atlas patch whose pixel payload is already RGBA8.
    pub(crate) fn new(region: AtlasRegion, pixels: Vec<u8>) -> Self {
        Self { region, pixels }
    }
}

/// Block-level scene cache mutation.
#[derive(Clone, Debug)]
pub(crate) enum BlockOp {
    Replace {
        block_id: BlockId,
        batch: BlockSceneBatch,
    },
    Remove {
        block_id: BlockId,
    },
}

/// Incremental scene update emitted by the async store toward the view.
#[derive(Clone, Debug)]
pub(crate) struct SceneDiff {
    pub(crate) viewport_revision: u64,
    pub(crate) requested_atlas_size: Option<u32>,
    pub(crate) atlas_patches: Vec<AtlasPatch>,
    pub(crate) clear_tessellation_cache: bool,
    pub(crate) block_order: Option<Vec<BlockId>>,
    pub(crate) block_ops: Vec<BlockOp>,
}

impl SceneDiff {
    /// Creates an empty diff associated with one viewport revision.
    pub(crate) fn new(viewport_revision: u64) -> Self {
        Self {
            viewport_revision,
            requested_atlas_size: None,
            atlas_patches: Vec::new(),
            clear_tessellation_cache: false,
            block_order: None,
            block_ops: Vec::new(),
        }
    }

    /// Returns whether the diff carries no externally visible scene change.
    pub(crate) fn is_empty(&self) -> bool {
        self.requested_atlas_size.is_none()
            && self.atlas_patches.is_empty()
            && !self.clear_tessellation_cache
            && self.block_order.is_none()
            && self.block_ops.is_empty()
    }
}
