//! Shared action and view-update payloads crossing the winit/async boundary.

use crate::renderer::atlas::AtlasRegion;
use crate::scene::{BlockId, BlockSceneBatch};

/// Wake-up event delivered through the winit event-loop proxy.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum WakeEvent {
    Wake,
}

/// High-level button state independent of the windowing backend.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum ButtonState {
    Pressed,
    Released,
}

/// High-level mouse button independent of the windowing backend.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum MouseButtonKind {
    Left,
    Right,
    Middle,
    Back,
    Forward,
    Other(u16),
}

/// High-level scroll payload independent of the windowing backend.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum MouseScroll {
    LineDelta { x: f32, y: f32 },
    PixelDelta { x: f64, y: f64 },
}

/// Unified input action sent from winit into the async store.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Action {
    KeyInput {
        text: String,
    },
    MouseButton {
        state: ButtonState,
        button: MouseButtonKind,
    },
    MouseMove {
        x: f64,
        y: f64,
    },
    MouseScroll {
        delta: MouseScroll,
    },
    Resize {
        width: u32,
        height: u32,
        scale_factor: f32,
        viewport_revision: u64,
    },
    Shutdown,
}

/// One atlas texture region write generated by the async logical atlas.
#[derive(Clone, Debug)]
pub(crate) struct AtlasPatch {
    pub(crate) region: AtlasRegion,
    pub(crate) pixels: Vec<u8>,
}

impl AtlasPatch {
    /// Creates one atlas patch whose pixel payload is already RGBA8.
    pub(crate) fn new(region: AtlasRegion, pixels: Vec<u8>) -> Self {
        Self { region, pixels }
    }
}

/// Block-level scene cache mutation.
#[derive(Clone, Debug)]
pub(crate) enum BlockOp {
    Replace {
        block_id: BlockId,
        batch: BlockSceneBatch,
    },
    Remove {
        block_id: BlockId,
    },
}

/// Incremental scene payload emitted by the async store toward the view.
#[derive(Clone, Debug)]
pub(crate) enum ScenePayload {
    ReplaceAll {
        block_order: Vec<BlockId>,
        block_batches: Vec<(BlockId, BlockSceneBatch)>,
    },
    Diff {
        block_order: Option<Vec<BlockId>>,
        block_ops: Vec<BlockOp>,
    },
}

impl ScenePayload {
    /// Returns whether the payload carries no externally visible scene change.
    pub(crate) fn is_empty(&self) -> bool {
        match self {
            Self::ReplaceAll { .. } => false,
            Self::Diff {
                block_order,
                block_ops,
            } => block_order.is_none() && block_ops.is_empty(),
        }
    }
}

/// Scene frame emitted by the async store toward the view.
#[derive(Clone, Debug)]
pub(crate) struct SceneFrame {
    pub(crate) viewport_revision: u64,
    pub(crate) required_atlas_generation: Option<u64>,
    pub(crate) clear_tessellation_cache: bool,
    pub(crate) payload: ScenePayload,
}

impl SceneFrame {
    /// Creates one scene frame associated with one viewport revision.
    pub(crate) fn new(
        viewport_revision: u64,
        required_atlas_generation: Option<u64>,
        payload: ScenePayload,
    ) -> Self {
        Self {
            viewport_revision,
            required_atlas_generation,
            clear_tessellation_cache: false,
            payload,
        }
    }

    /// Returns whether the frame carries no externally visible scene change.
    pub(crate) fn is_empty(&self) -> bool {
        !self.clear_tessellation_cache && self.payload.is_empty()
    }
}

/// One atlas update emitted by the async store toward the view.
#[derive(Clone, Debug)]
pub(crate) struct AtlasUpdate {
    pub(crate) generation: u64,
    pub(crate) requested_atlas_size: Option<u32>,
    pub(crate) patches: Vec<AtlasPatch>,
}

impl AtlasUpdate {
    /// Creates an empty atlas update for one logical atlas generation.
    pub(crate) fn new(generation: u64) -> Self {
        Self {
            generation,
            requested_atlas_size: None,
            patches: Vec::new(),
        }
    }
}

/// Unified async-to-view payload. Atlas and scene lifecycles are independent.
#[derive(Clone, Debug)]
pub(crate) enum ViewUpdate {
    Atlas(AtlasUpdate),
    Scene(SceneFrame),
}
